CREATE TABLE IF NOT EXISTS "guestbook" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guestbook_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar,
	"message" text,
	"rating" bigint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "web_vitals" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "web_vitals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"metric" varchar(8) NOT NULL,
	"value" double precision NOT NULL,
	"rating" varchar(20) NOT NULL,
	"path" varchar(256) NOT NULL,
	"locale" varchar(5) NOT NULL,
	"device" varchar(8) NOT NULL,
	"navigation_type" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "web_vitals_metric_created_at_idx" ON "web_vitals" USING btree ("metric","created_at");